from setuptools import setup

setup(
    name='fake_detector',
    version='1',
    packages=['venv.Lib.site-packages.boto', 'venv.Lib.site-packages.boto.gs', 'venv.Lib.site-packages.boto.s3',
              'venv.Lib.site-packages.boto.ec2', 'venv.Lib.site-packages.boto.ec2.elb',
              'venv.Lib.site-packages.boto.ec2.autoscale', 'venv.Lib.site-packages.boto.ec2.cloudwatch',
              'venv.Lib.site-packages.boto.ecs', 'venv.Lib.site-packages.boto.emr', 'venv.Lib.site-packages.boto.fps',
              'venv.Lib.site-packages.boto.iam', 'venv.Lib.site-packages.boto.kms', 'venv.Lib.site-packages.boto.mws',
              'venv.Lib.site-packages.boto.rds', 'venv.Lib.site-packages.boto.sdb',
              'venv.Lib.site-packages.boto.sdb.db', 'venv.Lib.site-packages.boto.sdb.db.manager',
              'venv.Lib.site-packages.boto.ses', 'venv.Lib.site-packages.boto.sns', 'venv.Lib.site-packages.boto.sqs',
              'venv.Lib.site-packages.boto.sts', 'venv.Lib.site-packages.boto.swf', 'venv.Lib.site-packages.boto.vpc',
              'venv.Lib.site-packages.boto.file', 'venv.Lib.site-packages.boto.logs',
              'venv.Lib.site-packages.boto.rds2', 'venv.Lib.site-packages.boto.mturk',
              'venv.Lib.site-packages.boto.pyami', 'venv.Lib.site-packages.boto.pyami.installers',
              'venv.Lib.site-packages.boto.pyami.installers.ubuntu', 'venv.Lib.site-packages.boto.manage',
              'venv.Lib.site-packages.boto.roboto', 'venv.Lib.site-packages.boto.cacerts',
              'venv.Lib.site-packages.boto.cognito', 'venv.Lib.site-packages.boto.cognito.sync',
              'venv.Lib.site-packages.boto.cognito.identity', 'venv.Lib.site-packages.boto.contrib',
              'venv.Lib.site-packages.boto.glacier', 'venv.Lib.site-packages.boto.kinesis',
              'venv.Lib.site-packages.boto.mashups', 'venv.Lib.site-packages.boto.route53',
              'venv.Lib.site-packages.boto.route53.domains', 'venv.Lib.site-packages.boto.support',
              'venv.Lib.site-packages.boto.cloudhsm', 'venv.Lib.site-packages.boto.dynamodb',
              'venv.Lib.site-packages.boto.opsworks', 'venv.Lib.site-packages.boto.redshift',
              'venv.Lib.site-packages.boto.services', 'venv.Lib.site-packages.boto.vendored',
              'venv.Lib.site-packages.boto.vendored.regions', 'venv.Lib.site-packages.boto.awslambda',
              'venv.Lib.site-packages.boto.beanstalk', 'venv.Lib.site-packages.boto.dynamodb2',
              'venv.Lib.site-packages.boto.cloudfront', 'venv.Lib.site-packages.boto.cloudtrail',
              'venv.Lib.site-packages.boto.codedeploy', 'venv.Lib.site-packages.boto.cloudsearch',
              'venv.Lib.site-packages.boto.elasticache', 'venv.Lib.site-packages.boto.cloudsearch2',
              'venv.Lib.site-packages.boto.datapipeline', 'venv.Lib.site-packages.boto.configservice',
              'venv.Lib.site-packages.boto.directconnect', 'venv.Lib.site-packages.boto.cloudformation',
              'venv.Lib.site-packages.boto.machinelearning', 'venv.Lib.site-packages.boto.cloudsearchdomain',
              'venv.Lib.site-packages.boto.elastictranscoder', 'venv.Lib.site-packages.boto.ec2containerservice',
              'venv.Lib.site-packages.cffi', 'venv.Lib.site-packages.idna', 'venv.Lib.site-packages.nltk',
              'venv.Lib.site-packages.nltk.app', 'venv.Lib.site-packages.nltk.ccg', 'venv.Lib.site-packages.nltk.sem',
              'venv.Lib.site-packages.nltk.tag', 'venv.Lib.site-packages.nltk.tbl', 'venv.Lib.site-packages.nltk.chat',
              'venv.Lib.site-packages.nltk.draw', 'venv.Lib.site-packages.nltk.misc',
              'venv.Lib.site-packages.nltk.stem', 'venv.Lib.site-packages.nltk.test',
              'venv.Lib.site-packages.nltk.test.unit', 'venv.Lib.site-packages.nltk.test.unit.translate',
              'venv.Lib.site-packages.nltk.chunk', 'venv.Lib.site-packages.nltk.parse',
              'venv.Lib.site-packages.nltk.corpus', 'venv.Lib.site-packages.nltk.corpus.reader',
              'venv.Lib.site-packages.nltk.cluster', 'venv.Lib.site-packages.nltk.metrics',
              'venv.Lib.site-packages.nltk.twitter', 'venv.Lib.site-packages.nltk.classify',
              'venv.Lib.site-packages.nltk.tokenize', 'venv.Lib.site-packages.nltk.inference',
              'venv.Lib.site-packages.nltk.sentiment', 'venv.Lib.site-packages.nltk.translate',
              'venv.Lib.site-packages.pytz', 'venv.Lib.site-packages.boto3', 'venv.Lib.site-packages.boto3.s3',
              'venv.Lib.site-packages.boto3.ec2', 'venv.Lib.site-packages.boto3.docs',
              'venv.Lib.site-packages.boto3.dynamodb', 'venv.Lib.site-packages.boto3.resources',
              'venv.Lib.site-packages.numpy', 'venv.Lib.site-packages.numpy.ma',
              'venv.Lib.site-packages.numpy.ma.tests', 'venv.Lib.site-packages.numpy.doc',
              'venv.Lib.site-packages.numpy.fft', 'venv.Lib.site-packages.numpy.fft.tests',
              'venv.Lib.site-packages.numpy.lib', 'venv.Lib.site-packages.numpy.lib.tests',
              'venv.Lib.site-packages.numpy.core', 'venv.Lib.site-packages.numpy.core.tests',
              'venv.Lib.site-packages.numpy.f2py', 'venv.Lib.site-packages.numpy.f2py.tests',
              'venv.Lib.site-packages.numpy.tests', 'venv.Lib.site-packages.numpy.compat',
              'venv.Lib.site-packages.numpy.compat.tests', 'venv.Lib.site-packages.numpy.linalg',
              'venv.Lib.site-packages.numpy.linalg.tests', 'venv.Lib.site-packages.numpy.random',
              'venv.Lib.site-packages.numpy.random.tests', 'venv.Lib.site-packages.numpy.testing',
              'venv.Lib.site-packages.numpy.testing.tests', 'venv.Lib.site-packages.numpy.testing._private',
              'venv.Lib.site-packages.numpy.distutils', 'venv.Lib.site-packages.numpy.distutils.tests',
              'venv.Lib.site-packages.numpy.distutils.command', 'venv.Lib.site-packages.numpy.distutils.fcompiler',
              'venv.Lib.site-packages.numpy.matrixlib', 'venv.Lib.site-packages.numpy.matrixlib.tests',
              'venv.Lib.site-packages.numpy.polynomial', 'venv.Lib.site-packages.numpy.polynomial.tests',
              'venv.Lib.site-packages.scipy', 'venv.Lib.site-packages.scipy.io', 'venv.Lib.site-packages.scipy.io.arff',
              'venv.Lib.site-packages.scipy.io.arff.tests', 'venv.Lib.site-packages.scipy.io.tests',
              'venv.Lib.site-packages.scipy.io.matlab', 'venv.Lib.site-packages.scipy.io.matlab.tests',
              'venv.Lib.site-packages.scipy.io.harwell_boeing', 'venv.Lib.site-packages.scipy.io.harwell_boeing.tests',
              'venv.Lib.site-packages.scipy.odr', 'venv.Lib.site-packages.scipy.odr.tests',
              'venv.Lib.site-packages.scipy._lib', 'venv.Lib.site-packages.scipy._lib.tests',
              'venv.Lib.site-packages.scipy.misc', 'venv.Lib.site-packages.scipy.misc.tests',
              'venv.Lib.site-packages.scipy.stats', 'venv.Lib.site-packages.scipy.stats.tests',
              'venv.Lib.site-packages.scipy.linalg', 'venv.Lib.site-packages.scipy.linalg.tests',
              'venv.Lib.site-packages.scipy.signal', 'venv.Lib.site-packages.scipy.signal.tests',
              'venv.Lib.site-packages.scipy.signal.windows', 'venv.Lib.site-packages.scipy.sparse',
              'venv.Lib.site-packages.scipy.sparse.tests', 'venv.Lib.site-packages.scipy.sparse.linalg',
              'venv.Lib.site-packages.scipy.sparse.linalg.eigen',
              'venv.Lib.site-packages.scipy.sparse.linalg.eigen.arpack',
              'venv.Lib.site-packages.scipy.sparse.linalg.eigen.arpack.tests',
              'venv.Lib.site-packages.scipy.sparse.linalg.eigen.lobpcg',
              'venv.Lib.site-packages.scipy.sparse.linalg.eigen.lobpcg.tests',
              'venv.Lib.site-packages.scipy.sparse.linalg.tests', 'venv.Lib.site-packages.scipy.sparse.linalg.dsolve',
              'venv.Lib.site-packages.scipy.sparse.linalg.dsolve.tests',
              'venv.Lib.site-packages.scipy.sparse.linalg.isolve',
              'venv.Lib.site-packages.scipy.sparse.linalg.isolve.tests', 'venv.Lib.site-packages.scipy.sparse.csgraph',
              'venv.Lib.site-packages.scipy.sparse.csgraph.tests', 'venv.Lib.site-packages.scipy.cluster',
              'venv.Lib.site-packages.scipy.cluster.tests', 'venv.Lib.site-packages.scipy.fftpack',
              'venv.Lib.site-packages.scipy.fftpack.tests', 'venv.Lib.site-packages.scipy.ndimage',
              'venv.Lib.site-packages.scipy.ndimage.tests', 'venv.Lib.site-packages.scipy.spatial',
              'venv.Lib.site-packages.scipy.spatial.tests', 'venv.Lib.site-packages.scipy.special',
              'venv.Lib.site-packages.scipy.special.tests', 'venv.Lib.site-packages.scipy.special._precompute',
              'venv.Lib.site-packages.scipy.optimize', 'venv.Lib.site-packages.scipy.optimize._lsq',
              'venv.Lib.site-packages.scipy.optimize.tests', 'venv.Lib.site-packages.scipy.optimize._trlib',
              'venv.Lib.site-packages.scipy.optimize._trustregion_constr',
              'venv.Lib.site-packages.scipy.optimize._trustregion_constr.tests',
              'venv.Lib.site-packages.scipy.constants', 'venv.Lib.site-packages.scipy.constants.tests',
              'venv.Lib.site-packages.scipy.integrate', 'venv.Lib.site-packages.scipy.integrate._ivp',
              'venv.Lib.site-packages.scipy.integrate.tests', 'venv.Lib.site-packages.scipy.interpolate',
              'venv.Lib.site-packages.scipy.interpolate.tests', 'venv.Lib.site-packages.scipy._build_utils',
              'venv.Lib.site-packages.gensim', 'venv.Lib.site-packages.gensim.viz',
              'venv.Lib.site-packages.gensim.test', 'venv.Lib.site-packages.gensim.models',
              'venv.Lib.site-packages.gensim.models.wrappers', 'venv.Lib.site-packages.gensim.models.deprecated',
              'venv.Lib.site-packages.gensim.corpora', 'venv.Lib.site-packages.gensim.parsing',
              'venv.Lib.site-packages.gensim.scripts', 'venv.Lib.site-packages.gensim.sklearn_api',
              'venv.Lib.site-packages.gensim.similarities', 'venv.Lib.site-packages.gensim.summarization',
              'venv.Lib.site-packages.gensim.topic_coherence', 'venv.Lib.site-packages.pandas',
              'venv.Lib.site-packages.pandas.io', 'venv.Lib.site-packages.pandas.io.sas',
              'venv.Lib.site-packages.pandas.io.json', 'venv.Lib.site-packages.pandas.io.formats',
              'venv.Lib.site-packages.pandas.io.msgpack', 'venv.Lib.site-packages.pandas.io.clipboard',
              'venv.Lib.site-packages.pandas.api', 'venv.Lib.site-packages.pandas.api.types',
              'venv.Lib.site-packages.pandas.api.extensions', 'venv.Lib.site-packages.pandas.core',
              'venv.Lib.site-packages.pandas.core.util', 'venv.Lib.site-packages.pandas.core.tools',
              'venv.Lib.site-packages.pandas.core.arrays', 'venv.Lib.site-packages.pandas.core.dtypes',
              'venv.Lib.site-packages.pandas.core.sparse', 'venv.Lib.site-packages.pandas.core.groupby',
              'venv.Lib.site-packages.pandas.core.indexes', 'venv.Lib.site-packages.pandas.core.reshape',
              'venv.Lib.site-packages.pandas.core.computation', 'venv.Lib.site-packages.pandas.util',
              'venv.Lib.site-packages.pandas._libs', 'venv.Lib.site-packages.pandas._libs.tslibs',
              'venv.Lib.site-packages.pandas.tests', 'venv.Lib.site-packages.pandas.tests.io',
              'venv.Lib.site-packages.pandas.tests.io.sas', 'venv.Lib.site-packages.pandas.tests.io.json',
              'venv.Lib.site-packages.pandas.tests.io.parser', 'venv.Lib.site-packages.pandas.tests.io.formats',
              'venv.Lib.site-packages.pandas.tests.io.msgpack', 'venv.Lib.site-packages.pandas.tests.api',
              'venv.Lib.site-packages.pandas.tests.util', 'venv.Lib.site-packages.pandas.tests.frame',
              'venv.Lib.site-packages.pandas.tests.tools', 'venv.Lib.site-packages.pandas.tests.dtypes',
              'venv.Lib.site-packages.pandas.tests.scalar', 'venv.Lib.site-packages.pandas.tests.scalar.period',
              'venv.Lib.site-packages.pandas.tests.scalar.interval',
              'venv.Lib.site-packages.pandas.tests.scalar.timedelta',
              'venv.Lib.site-packages.pandas.tests.scalar.timestamp', 'venv.Lib.site-packages.pandas.tests.series',
              'venv.Lib.site-packages.pandas.tests.series.indexing', 'venv.Lib.site-packages.pandas.tests.sparse',
              'venv.Lib.site-packages.pandas.tests.sparse.frame', 'venv.Lib.site-packages.pandas.tests.sparse.series',
              'venv.Lib.site-packages.pandas.tests.tslibs', 'venv.Lib.site-packages.pandas.tests.generic',
              'venv.Lib.site-packages.pandas.tests.groupby', 'venv.Lib.site-packages.pandas.tests.groupby.aggregate',
              'venv.Lib.site-packages.pandas.tests.indexes', 'venv.Lib.site-packages.pandas.tests.indexes.period',
              'venv.Lib.site-packages.pandas.tests.indexes.interval',
              'venv.Lib.site-packages.pandas.tests.indexes.datetimes',
              'venv.Lib.site-packages.pandas.tests.indexes.timedeltas', 'venv.Lib.site-packages.pandas.tests.reshape',
              'venv.Lib.site-packages.pandas.tests.reshape.merge', 'venv.Lib.site-packages.pandas.tests.tseries',
              'venv.Lib.site-packages.pandas.tests.tseries.offsets', 'venv.Lib.site-packages.pandas.tests.indexing',
              'venv.Lib.site-packages.pandas.tests.indexing.interval', 'venv.Lib.site-packages.pandas.tests.plotting',
              'venv.Lib.site-packages.pandas.tests.extension', 'venv.Lib.site-packages.pandas.tests.extension.base',
              'venv.Lib.site-packages.pandas.tests.extension.json',
              'venv.Lib.site-packages.pandas.tests.extension.decimal',
              'venv.Lib.site-packages.pandas.tests.extension.category', 'venv.Lib.site-packages.pandas.tests.internals',
              'venv.Lib.site-packages.pandas.tests.categorical', 'venv.Lib.site-packages.pandas.tests.computation',
              'venv.Lib.site-packages.pandas.tools', 'venv.Lib.site-packages.pandas.types',
              'venv.Lib.site-packages.pandas.compat', 'venv.Lib.site-packages.pandas.compat.numpy',
              'venv.Lib.site-packages.pandas.errors', 'venv.Lib.site-packages.pandas.formats',
              'venv.Lib.site-packages.pandas.tseries', 'venv.Lib.site-packages.pandas.plotting',
              'venv.Lib.site-packages.pandas.computation', 'venv.Lib.site-packages.certifi',
              'venv.Lib.site-packages.chardet', 'venv.Lib.site-packages.chardet.cli', 'venv.Lib.site-packages.pymysql',
              'venv.Lib.site-packages.pymysql.constants', 'venv.Lib.site-packages.seaborn',
              'venv.Lib.site-packages.seaborn.tests', 'venv.Lib.site-packages.seaborn.colors',
              'venv.Lib.site-packages.seaborn.external', 'venv.Lib.site-packages.sklearn',
              'venv.Lib.site-packages.sklearn.svm', 'venv.Lib.site-packages.sklearn.svm.tests',
              'venv.Lib.site-packages.sklearn.tree', 'venv.Lib.site-packages.sklearn.tree.tests',
              'venv.Lib.site-packages.sklearn.tests', 'venv.Lib.site-packages.sklearn.utils',
              'venv.Lib.site-packages.sklearn.utils.tests', 'venv.Lib.site-packages.sklearn.utils.sparsetools',
              'venv.Lib.site-packages.sklearn.utils.sparsetools.tests', 'venv.Lib.site-packages.sklearn.cluster',
              'venv.Lib.site-packages.sklearn.cluster.tests', 'venv.Lib.site-packages.sklearn.compose',
              'venv.Lib.site-packages.sklearn.compose.tests', 'venv.Lib.site-packages.sklearn.metrics',
              'venv.Lib.site-packages.sklearn.metrics.tests', 'venv.Lib.site-packages.sklearn.metrics.cluster',
              'venv.Lib.site-packages.sklearn.metrics.cluster.tests', 'venv.Lib.site-packages.sklearn.mixture',
              'venv.Lib.site-packages.sklearn.mixture.tests', 'venv.Lib.site-packages.sklearn.datasets',
              'venv.Lib.site-packages.sklearn.datasets.tests', 'venv.Lib.site-packages.sklearn.ensemble',
              'venv.Lib.site-packages.sklearn.ensemble.tests', 'venv.Lib.site-packages.sklearn.manifold',
              'venv.Lib.site-packages.sklearn.manifold.tests', 'venv.Lib.site-packages.sklearn.externals',
              'venv.Lib.site-packages.sklearn.externals.joblib',
              'venv.Lib.site-packages.sklearn.externals.joblib.externals',
              'venv.Lib.site-packages.sklearn.externals.joblib.externals.loky',
              'venv.Lib.site-packages.sklearn.externals.joblib.externals.loky.backend',
              'venv.Lib.site-packages.sklearn.externals.joblib.externals.cloudpickle',
              'venv.Lib.site-packages.sklearn.neighbors', 'venv.Lib.site-packages.sklearn.neighbors.tests',
              'venv.Lib.site-packages.sklearn.covariance', 'venv.Lib.site-packages.sklearn.covariance.tests',
              'venv.Lib.site-packages.sklearn._build_utils', 'venv.Lib.site-packages.sklearn.linear_model',
              'venv.Lib.site-packages.sklearn.linear_model.tests', 'venv.Lib.site-packages.sklearn.__check_build',
              'venv.Lib.site-packages.sklearn.decomposition', 'venv.Lib.site-packages.sklearn.decomposition.tests',
              'venv.Lib.site-packages.sklearn.preprocessing', 'venv.Lib.site-packages.sklearn.preprocessing.tests',
              'venv.Lib.site-packages.sklearn.neural_network', 'venv.Lib.site-packages.sklearn.neural_network.tests',
              'venv.Lib.site-packages.sklearn.model_selection', 'venv.Lib.site-packages.sklearn.model_selection.tests',
              'venv.Lib.site-packages.sklearn.semi_supervised', 'venv.Lib.site-packages.sklearn.semi_supervised.tests',
              'venv.Lib.site-packages.sklearn.gaussian_process',
              'venv.Lib.site-packages.sklearn.gaussian_process.tests',
              'venv.Lib.site-packages.sklearn.feature_selection',
              'venv.Lib.site-packages.sklearn.feature_selection.tests',
              'venv.Lib.site-packages.sklearn.feature_extraction',
              'venv.Lib.site-packages.sklearn.feature_extraction.tests',
              'venv.Lib.site-packages.sklearn.cross_decomposition',
              'venv.Lib.site-packages.sklearn.cross_decomposition.tests', 'venv.Lib.site-packages.urllib3',
              'venv.Lib.site-packages.urllib3.util', 'venv.Lib.site-packages.urllib3.contrib',
              'venv.Lib.site-packages.urllib3.contrib._securetransport', 'venv.Lib.site-packages.urllib3.packages',
              'venv.Lib.site-packages.urllib3.packages.backports',
              'venv.Lib.site-packages.urllib3.packages.ssl_match_hostname', 'venv.Lib.site-packages.botocore',
              'venv.Lib.site-packages.botocore.docs', 'venv.Lib.site-packages.botocore.docs.bcdoc',
              'venv.Lib.site-packages.botocore.vendored', 'venv.Lib.site-packages.botocore.vendored.requests',
              'venv.Lib.site-packages.botocore.vendored.requests.packages',
              'venv.Lib.site-packages.botocore.vendored.requests.packages.chardet',
              'venv.Lib.site-packages.botocore.vendored.requests.packages.urllib3',
              'venv.Lib.site-packages.botocore.vendored.requests.packages.urllib3.util',
              'venv.Lib.site-packages.botocore.vendored.requests.packages.urllib3.contrib',
              'venv.Lib.site-packages.botocore.vendored.requests.packages.urllib3.packages',
              'venv.Lib.site-packages.botocore.vendored.requests.packages.urllib3.packages.ssl_match_hostname',
              'venv.Lib.site-packages.dateutil', 'venv.Lib.site-packages.dateutil.tz',
              'venv.Lib.site-packages.dateutil.parser', 'venv.Lib.site-packages.dateutil.zoneinfo',
              'venv.Lib.site-packages.docutils', 'venv.Lib.site-packages.docutils.utils',
              'venv.Lib.site-packages.docutils.utils.math', 'venv.Lib.site-packages.docutils.parsers',
              'venv.Lib.site-packages.docutils.parsers.rst', 'venv.Lib.site-packages.docutils.parsers.rst.languages',
              'venv.Lib.site-packages.docutils.parsers.rst.directives', 'venv.Lib.site-packages.docutils.readers',
              'venv.Lib.site-packages.docutils.writers', 'venv.Lib.site-packages.docutils.writers.xetex',
              'venv.Lib.site-packages.docutils.writers.latex2e', 'venv.Lib.site-packages.docutils.writers.odf_odt',
              'venv.Lib.site-packages.docutils.writers.s5_html', 'venv.Lib.site-packages.docutils.writers.pep_html',
              'venv.Lib.site-packages.docutils.writers.html4css1',
              'venv.Lib.site-packages.docutils.writers.html5_polyglot', 'venv.Lib.site-packages.docutils.languages',
              'venv.Lib.site-packages.docutils.transforms', 'venv.Lib.site-packages.jmespath',
              'venv.Lib.site-packages.requests', 'venv.Lib.site-packages.pycparser',
              'venv.Lib.site-packages.pycparser.ply', 'venv.Lib.site-packages.asn1crypto',
              'venv.Lib.site-packages.asn1crypto._perf', 'venv.Lib.site-packages.matplotlib',
              'venv.Lib.site-packages.matplotlib.tri', 'venv.Lib.site-packages.matplotlib.axes',
              'venv.Lib.site-packages.matplotlib.cbook', 'venv.Lib.site-packages.matplotlib.style',
              'venv.Lib.site-packages.matplotlib.compat', 'venv.Lib.site-packages.matplotlib.testing',
              'venv.Lib.site-packages.matplotlib.testing.jpl_units', 'venv.Lib.site-packages.matplotlib.backends',
              'venv.Lib.site-packages.matplotlib.backends.qt_editor', 'venv.Lib.site-packages.matplotlib.sphinxext',
              'venv.Lib.site-packages.matplotlib.projections', 'venv.Lib.site-packages.s3transfer',
              'venv.Lib.site-packages.smart_open', 'venv.Lib.site-packages.smart_open.tests',
              'venv.Lib.site-packages.sqlalchemy', 'venv.Lib.site-packages.sqlalchemy.ext',
              'venv.Lib.site-packages.sqlalchemy.ext.declarative', 'venv.Lib.site-packages.sqlalchemy.orm',
              'venv.Lib.site-packages.sqlalchemy.sql', 'venv.Lib.site-packages.sqlalchemy.util',
              'venv.Lib.site-packages.sqlalchemy.event', 'venv.Lib.site-packages.sqlalchemy.engine',
              'venv.Lib.site-packages.sqlalchemy.testing', 'venv.Lib.site-packages.sqlalchemy.testing.suite',
              'venv.Lib.site-packages.sqlalchemy.testing.plugin', 'venv.Lib.site-packages.sqlalchemy.dialects',
              'venv.Lib.site-packages.sqlalchemy.dialects.mssql', 'venv.Lib.site-packages.sqlalchemy.dialects.mysql',
              'venv.Lib.site-packages.sqlalchemy.dialects.oracle', 'venv.Lib.site-packages.sqlalchemy.dialects.sqlite',
              'venv.Lib.site-packages.sqlalchemy.dialects.sybase',
              'venv.Lib.site-packages.sqlalchemy.dialects.firebird',
              'venv.Lib.site-packages.sqlalchemy.dialects.postgresql', 'venv.Lib.site-packages.sqlalchemy.databases',
              'venv.Lib.site-packages.sqlalchemy.connectors', 'venv.Lib.site-packages.cryptography',
              'venv.Lib.site-packages.cryptography.x509', 'venv.Lib.site-packages.cryptography.hazmat',
              'venv.Lib.site-packages.cryptography.hazmat.backends',
              'venv.Lib.site-packages.cryptography.hazmat.backends.openssl',
              'venv.Lib.site-packages.cryptography.hazmat.bindings',
              'venv.Lib.site-packages.cryptography.hazmat.bindings.openssl',
              'venv.Lib.site-packages.cryptography.hazmat.primitives',
              'venv.Lib.site-packages.cryptography.hazmat.primitives.kdf',
              'venv.Lib.site-packages.cryptography.hazmat.primitives.ciphers',
              'venv.Lib.site-packages.cryptography.hazmat.primitives.twofactor',
              'venv.Lib.site-packages.cryptography.hazmat.primitives.asymmetric',
              'venv.Lib.site-packages.mpl_toolkits.mplot3d', 'venv.Lib.site-packages.mpl_toolkits.axes_grid',
              'venv.Lib.site-packages.mpl_toolkits.axes_grid1', 'venv.Lib.site-packages.mpl_toolkits.axisartist',
              'venv.Lib.site-packages.pip-10.0.1-py3.7.egg.pip',
              'venv.Lib.site-packages.pip-10.0.1-py3.7.egg.pip._vendor',
              'venv.Lib.site-packages.pip-10.0.1-py3.7.egg.pip._vendor.idna',
              'venv.Lib.site-packages.pip-10.0.1-py3.7.egg.pip._vendor.pytoml',
              'venv.Lib.site-packages.pip-10.0.1-py3.7.egg.pip._vendor.certifi',
              'venv.Lib.site-packages.pip-10.0.1-py3.7.egg.pip._vendor.chardet',
              'venv.Lib.site-packages.pip-10.0.1-py3.7.egg.pip._vendor.chardet.cli',
              'venv.Lib.site-packages.pip-10.0.1-py3.7.egg.pip._vendor.distlib',
              'venv.Lib.site-packages.pip-10.0.1-py3.7.egg.pip._vendor.distlib._backport',
              'venv.Lib.site-packages.pip-10.0.1-py3.7.egg.pip._vendor.msgpack',
              'venv.Lib.site-packages.pip-10.0.1-py3.7.egg.pip._vendor.urllib3',
              'venv.Lib.site-packages.pip-10.0.1-py3.7.egg.pip._vendor.urllib3.util',
              'venv.Lib.site-packages.pip-10.0.1-py3.7.egg.pip._vendor.urllib3.contrib',
              'venv.Lib.site-packages.pip-10.0.1-py3.7.egg.pip._vendor.urllib3.contrib._securetransport',
              'venv.Lib.site-packages.pip-10.0.1-py3.7.egg.pip._vendor.urllib3.packages',
              'venv.Lib.site-packages.pip-10.0.1-py3.7.egg.pip._vendor.urllib3.packages.backports',
              'venv.Lib.site-packages.pip-10.0.1-py3.7.egg.pip._vendor.urllib3.packages.ssl_match_hostname',
              'venv.Lib.site-packages.pip-10.0.1-py3.7.egg.pip._vendor.colorama',
              'venv.Lib.site-packages.pip-10.0.1-py3.7.egg.pip._vendor.html5lib',
              'venv.Lib.site-packages.pip-10.0.1-py3.7.egg.pip._vendor.html5lib._trie',
              'venv.Lib.site-packages.pip-10.0.1-py3.7.egg.pip._vendor.html5lib.filters',
              'venv.Lib.site-packages.pip-10.0.1-py3.7.egg.pip._vendor.html5lib.treewalkers',
              'venv.Lib.site-packages.pip-10.0.1-py3.7.egg.pip._vendor.html5lib.treeadapters',
              'venv.Lib.site-packages.pip-10.0.1-py3.7.egg.pip._vendor.html5lib.treebuilders',
              'venv.Lib.site-packages.pip-10.0.1-py3.7.egg.pip._vendor.lockfile',
              'venv.Lib.site-packages.pip-10.0.1-py3.7.egg.pip._vendor.progress',
              'venv.Lib.site-packages.pip-10.0.1-py3.7.egg.pip._vendor.requests',
              'venv.Lib.site-packages.pip-10.0.1-py3.7.egg.pip._vendor.packaging',
              'venv.Lib.site-packages.pip-10.0.1-py3.7.egg.pip._vendor.cachecontrol',
              'venv.Lib.site-packages.pip-10.0.1-py3.7.egg.pip._vendor.cachecontrol.caches',
              'venv.Lib.site-packages.pip-10.0.1-py3.7.egg.pip._vendor.webencodings',
              'venv.Lib.site-packages.pip-10.0.1-py3.7.egg.pip._vendor.pkg_resources',
              'venv.Lib.site-packages.pip-10.0.1-py3.7.egg.pip._internal',
              'venv.Lib.site-packages.pip-10.0.1-py3.7.egg.pip._internal.req',
              'venv.Lib.site-packages.pip-10.0.1-py3.7.egg.pip._internal.vcs',
              'venv.Lib.site-packages.pip-10.0.1-py3.7.egg.pip._internal.utils',
              'venv.Lib.site-packages.pip-10.0.1-py3.7.egg.pip._internal.models',
              'venv.Lib.site-packages.pip-10.0.1-py3.7.egg.pip._internal.commands',
              'venv.Lib.site-packages.pip-10.0.1-py3.7.egg.pip._internal.operations'],
    url='',
    license='',
    author='vishwa',
    author_email='',
    description=''
)
